import type { Annotation, RecordingRef, ReviewSession } from "./model";
import { MAX_NOTE_TEXT, MAX_POINTS, MAX_RECORDING_BYTES, MAX_RECORDING_MS, safeUrl } from "./pure";

export const RAW_MAGIC = new Uint8Array([0x50, 0x50, 0x52, 0x41, 0x57, 0x0d, 0x0a, 0x1a]);
export const RAW_VERSION = 1;
export const MAX_RAW_HEADER_BYTES = 5 * 1024 * 1024;
export const MAX_RAW_ARCHIVE_BYTES = 2 * 1024 * 1024 * 1024;
export const MAX_RAW_ANNOTATIONS = 10_000;
export const MAX_RAW_ASSETS = 2_000;
export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export type RawAssetKind = "screenshot" | "recording";
export interface RawAsset { sourceId: string; kind: RawAssetKind; mimeType: "image/jpeg" | "video/webm"; byteSize: number; crc32: string }
export interface RawManifest { format: "product-pass-raw-capture"; version: 1; exportedAt: number; session: Omit<ReviewSession, "id" | "drafts"> & { sourceId: string }; assets: RawAsset[] }
export interface ParsedRawCapture { manifest: RawManifest; payloadStart: number }
export interface RemappedRawCapture { session: ReviewSession; assets: RawAsset[]; screenshotIds: string[]; recordingIds: string[] }
const encoder = new TextEncoder(); const decoder = new TextDecoder("utf-8", { fatal: true });
function fail(message: string): never { throw new Error(`Invalid raw capture: ${message}`); }
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) fail("expected object"); return value as Record<string, unknown>; }
function str(value: unknown, name: string, max: number): string { if (typeof value !== "string" || value.length > max) fail(`invalid ${name}`); return value; }
function nonEmpty(value: unknown, name: string, max: number): string { const result = str(value, name, max); if (!result) fail(`invalid ${name}`); return result; }
function integer(value: unknown, name: string, min: number, max: number): number { if (!Number.isSafeInteger(value) || (value as number) < min || (value as number) > max) fail(`invalid ${name}`); return value as number; }
function id(value: unknown, name: string): string { const result = str(value, name, 36); if (!UUID.test(result)) fail(`invalid ${name}`); return result; }
function timestamp(value: unknown, name: string): number { return integer(value, name, 1, Date.now() + 60_000); }
function exactRect(value: unknown): { x: number; y: number; width: number; height: number } { const item = object(value); const x = item.x; const y = item.y; const width = item.width; const height = item.height; if (![x, y, width, height].every(Number.isFinite) || Math.abs(x as number) > 10_000_000 || Math.abs(y as number) > 10_000_000 || (width as number) < 0 || (height as number) < 0 || (width as number) > 100_000 || (height as number) > 100_000) fail("invalid rectangle"); return { x: x as number, y: y as number, width: width as number, height: height as number }; }
function exactPoints(value: unknown): Array<{ x: number; y: number }> { if (!Array.isArray(value) || value.length < 3 || value.length > MAX_POINTS) fail("invalid freehand anchor"); return value.map(point => { const item = object(point); if (!Number.isFinite(item.x) || !Number.isFinite(item.y) || Math.abs(item.x as number) > 10_000_000 || Math.abs(item.y as number) > 10_000_000) fail("invalid freehand point"); return { x: item.x as number, y: item.y as number }; }); }
function crc(value: unknown): string { const result = str(value, "CRC32", 8); if (!/^[0-9a-f]{8}$/.test(result)) fail("invalid CRC32"); return result; }
function rawAsset(value: unknown): RawAsset { const item = object(value); const kind = item.kind; const mimeType = item.mimeType; if ((kind !== "screenshot" && kind !== "recording") || (kind === "screenshot" && mimeType !== "image/jpeg") || (kind === "recording" && mimeType !== "video/webm")) fail("asset type"); return { sourceId: id(item.sourceId, "asset id"), kind: kind as RawAssetKind, mimeType: mimeType as RawAsset["mimeType"], byteSize: integer(item.byteSize, "asset size", 1, kind === "screenshot" ? MAX_IMAGE_BYTES : MAX_RECORDING_BYTES), crc32: crc(item.crc32) }; }
function validHttpUrl(value: string): boolean { try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:"; } catch { return false; } }
function validAnnotation(value: unknown, screenshotIds: Set<string>, recordings: Map<string, RecordingRef>): Annotation {
  const item = object(value); const annotationId = id(item.id, "annotation id"); const kind = item.kind;
  if (kind !== "element" && kind !== "freehand" && kind !== "video") fail("invalid annotation kind");
  const url = str(item.url, "annotation URL", 5_000); if (url && !validHttpUrl(url)) fail("invalid annotation URL"); if (!url && kind !== "video") fail("invalid annotation URL");
  const base = { id: annotationId, sessionId: id(item.sessionId, "annotation session"), kind, url: safeUrl(url), safeUrl: safeUrl(url), pageTitle: str(item.pageTitle, "page title", 300), text: str(item.text, "note text", MAX_NOTE_TEXT), contextLabel: str(item.contextLabel, "context", 160), createdAt: timestamp(item.createdAt, "annotation createdAt"), updatedAt: timestamp(item.updatedAt, "annotation updatedAt") } as Annotation;
  const anchor = object(item.anchor);
  if (kind === "element") { if (anchor.kind !== "element") fail("invalid element anchor"); base.anchor = { kind, selector: str(anchor.selector, "selector", 1_000), quote: str(anchor.quote, "quote", 160), rect: exactRect(anchor.rect) }; }
  else if (kind === "freehand") { if (anchor.kind !== "freehand") fail("invalid freehand anchor"); base.anchor = { kind, points: exactPoints(anchor.points), bounds: exactRect(anchor.bounds) }; }
  else { const recordingId = id(anchor.recordingId, "recording reference"); const recording = recordings.get(recordingId); if (anchor.kind !== "video" || !recording) fail("dangling recording reference"); base.anchor = { kind, recordingId, timestampMs: integer(anchor.timestampMs, "recording timestamp", 0, recording.durationMs) }; }
  if (item.screenshot !== undefined) { const shot = object(item.screenshot); const screenshotId = id(shot.id, "screenshot reference"); if (!screenshotIds.has(screenshotId) || shot.mimeType !== "image/jpeg") fail("dangling screenshot reference"); base.screenshot = { id: screenshotId, mimeType: "image/jpeg", width: integer(shot.width, "screenshot width", 1, 20_000), height: integer(shot.height, "screenshot height", 1, 20_000), createdAt: timestamp(shot.createdAt, "screenshot createdAt") }; }
  return base;
}
export function buildRawManifest(session: ReviewSession, assets: RawAsset[], exportedAt = Date.now()): RawManifest {
  const annotations = session.annotations.map(note => {
    const url = safeUrl(note.url); const anchor = note.anchor.kind === "element" ? { kind: "element" as const, selector: note.anchor.selector, quote: note.anchor.quote, rect: exactRect(note.anchor.rect) } : note.anchor.kind === "freehand" ? { kind: "freehand" as const, points: exactPoints(note.anchor.points), bounds: exactRect(note.anchor.bounds) } : { kind: "video" as const, recordingId: note.anchor.recordingId, timestampMs: note.anchor.timestampMs };
    return { id: note.id, sessionId: note.sessionId, kind: note.kind, url, safeUrl: url, pageTitle: note.pageTitle, text: note.text, contextLabel: note.contextLabel, anchor, ...(note.screenshot ? { screenshot: { ...note.screenshot } } : {}), createdAt: note.createdAt, updatedAt: note.updatedAt } as Annotation;
  });
  return { format: "product-pass-raw-capture", version: 1, exportedAt, session: { sourceId: session.id, title: session.title, status: session.status, annotations, recordings: session.recordings.map(recording => ({ ...recording })), createdAt: session.createdAt, updatedAt: session.updatedAt }, assets: assets.map(asset => ({ ...asset })) };
}
export function encodeRawPrefix(manifest: RawManifest): Uint8Array { const header = encoder.encode(JSON.stringify(manifest)); if (header.byteLength > MAX_RAW_HEADER_BYTES) fail("header is too large"); const output = new Uint8Array(RAW_MAGIC.length + 4 + header.byteLength); output.set(RAW_MAGIC); new DataView(output.buffer).setUint32(RAW_MAGIC.length, header.byteLength, true); output.set(header, RAW_MAGIC.length + 4); return output; }
export function parseRawCaptureHeader(prefix: Uint8Array, fileSize: number): ParsedRawCapture {
  if (!Number.isSafeInteger(fileSize) || fileSize < RAW_MAGIC.length + 4 || fileSize > MAX_RAW_ARCHIVE_BYTES) fail("archive size"); if (prefix.byteLength < RAW_MAGIC.length + 4) fail("truncated prefix"); for (let index = 0; index < RAW_MAGIC.length; index++) if (prefix[index] !== RAW_MAGIC[index]) fail("magic");
  const length = new DataView(prefix.buffer, prefix.byteOffset, prefix.byteLength).getUint32(RAW_MAGIC.length, true); if (length > MAX_RAW_HEADER_BYTES || RAW_MAGIC.length + 4 + length > fileSize || prefix.byteLength < RAW_MAGIC.length + 4 + length) fail("header length");
  let value: Record<string, unknown>; try { value = object(JSON.parse(decoder.decode(prefix.slice(RAW_MAGIC.length + 4, RAW_MAGIC.length + 4 + length)))); } catch { fail("header JSON"); }
  if (value.format !== "product-pass-raw-capture" || value.version !== RAW_VERSION || !Array.isArray(value.assets)) fail("format version"); const assets = value.assets.map(rawAsset); if (assets.length > MAX_RAW_ASSETS || new Set(assets.map(asset => asset.sourceId)).size !== assets.length) fail("duplicate assets"); const payloadSize = assets.reduce((total, asset) => total + asset.byteSize, 0); if (!Number.isSafeInteger(payloadSize) || RAW_MAGIC.length + 4 + length + payloadSize !== fileSize) fail("payload length");
  const session = object(value.session); const recordingsSource = Array.isArray(session.recordings) ? session.recordings : fail("recordings"); const annotationsSource = Array.isArray(session.annotations) ? session.annotations : fail("annotations"); if (annotationsSource.length > MAX_RAW_ANNOTATIONS) fail("annotation count"); const recordingAssets = new Map(assets.filter(asset => asset.kind === "recording").map(asset => [asset.sourceId, asset])); const screenshotIds = new Set(assets.filter(asset => asset.kind === "screenshot").map(asset => asset.sourceId));
  const sourceSessionId = id(session.sourceId, "session id"); const recordings = recordingsSource.map(value => { const item = object(value); const recordingId = id(item.id, "recording id"); const asset = recordingAssets.get(recordingId); if (!asset || item.mimeType !== "video/webm" || integer(item.byteSize, "recording size", 1, MAX_RECORDING_BYTES) !== asset.byteSize) fail("dangling recording"); return { id: recordingId, mimeType: "video/webm" as const, byteSize: asset.byteSize, durationMs: integer(item.durationMs, "recording duration", 1, MAX_RECORDING_MS), createdAt: timestamp(item.createdAt, "recording createdAt") }; });
  if (new Set(recordings.map(recording => recording.id)).size !== recordings.length || recordings.length !== recordingAssets.size) fail("recording IDs"); const recordingMap = new Map(recordings.map(recording => [recording.id, recording])); const annotations = annotationsSource.map(value => validAnnotation(value, screenshotIds, recordingMap)); if (annotations.some(annotation => annotation.sessionId !== sourceSessionId) || new Set(annotations.map(annotation => annotation.id)).size !== annotations.length) fail("annotation IDs"); const referencedShots = new Set(annotations.flatMap(annotation => annotation.screenshot ? [annotation.screenshot.id] : [])); if (referencedShots.size !== screenshotIds.size) fail("orphan screenshot");
  return { manifest: { format: "product-pass-raw-capture", version: 1, exportedAt: timestamp(value.exportedAt, "export time"), session: { sourceId: sourceSessionId, title: nonEmpty(session.title, "session title", 120), status: session.status === "capturing" || session.status === "reviewing" || session.status === "complete" ? session.status : fail("session status"), annotations, recordings, createdAt: timestamp(session.createdAt, "session createdAt"), updatedAt: timestamp(session.updatedAt, "session updatedAt") }, assets }, payloadStart: RAW_MAGIC.length + 4 + length };
}
export function projectImportedRawSession(value: unknown, assets: RawAsset[]): ReviewSession {
  const candidate = object(value); if (candidate.status !== "capturing") fail("imported session status"); const session = { ...candidate, sourceId: candidate.id };
  const payload = assets.reduce((total, asset) => total + asset.byteSize, 0); const header = encodeRawPrefix({ format: "product-pass-raw-capture", version: 1, exportedAt: Date.now(), session, assets } as RawManifest);
  const parsed = parseRawCaptureHeader(header, header.byteLength + payload).manifest;
  return { id: parsed.session.sourceId, title: parsed.session.title, status: "capturing", annotations: parsed.session.annotations, recordings: parsed.session.recordings, drafts: [], createdAt: parsed.session.createdAt, updatedAt: parsed.session.updatedAt };
}
export function remapRawCapture(manifest: RawManifest, generateId: () => string = () => crypto.randomUUID()): RemappedRawCapture { const sessionId = generateId(); const assets = manifest.assets.map(asset => ({ ...asset, sourceId: generateId() })); const map = new Map(manifest.assets.map((asset, index) => [asset.sourceId, assets[index].sourceId])); const recordings = manifest.session.recordings.map(recording => ({ ...recording, id: map.get(recording.id)! })); const annotations = manifest.session.annotations.map(note => ({ ...note, id: generateId(), sessionId, safeUrl: safeUrl(note.url), url: safeUrl(note.url), anchor: note.anchor.kind === "element" ? { ...note.anchor, rect: exactRect(note.anchor.rect) } : note.anchor.kind === "freehand" ? { ...note.anchor, points: exactPoints(note.anchor.points), bounds: exactRect(note.anchor.bounds) } : { ...note.anchor, recordingId: map.get(note.anchor.recordingId)! }, ...(note.screenshot ? { screenshot: { ...note.screenshot, id: map.get(note.screenshot.id)! } } : {}) })); return { session: { id: sessionId, title: manifest.session.title, status: "capturing", annotations, recordings, drafts: [], createdAt: manifest.session.createdAt, updatedAt: manifest.session.updatedAt }, assets, screenshotIds: assets.filter(asset => asset.kind === "screenshot").map(asset => asset.sourceId), recordingIds: assets.filter(asset => asset.kind === "recording").map(asset => asset.sourceId) }; }
const crcTable = new Uint32Array(256).map((_, index) => { let value = index; for (let bit = 0; bit < 8; bit++) value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1; return value >>> 0; });
export async function blobCrc32(blob: Blob): Promise<string> { let crcValue = 0xffffffff; const chunkSize = 64 * 1024; for (let offset = 0; offset < blob.size; offset += chunkSize) { const bytes = new Uint8Array(await blob.slice(offset, offset + chunkSize).arrayBuffer()); for (const byte of bytes) crcValue = crcTable[(crcValue ^ byte) & 0xff] ^ (crcValue >>> 8); } return ((crcValue ^ 0xffffffff) >>> 0).toString(16).padStart(8, "0"); }
export async function validRawAssetBlob(asset: RawAsset, blob: Blob): Promise<boolean> { if (blob.size !== asset.byteSize || blob.type !== asset.mimeType) return false; const bytes = new Uint8Array(await blob.slice(0, 4).arrayBuffer()); const signed = asset.kind === "screenshot" ? bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff : bytes.length >= 4 && bytes[0] === 0x1a && bytes[1] === 0x45 && bytes[2] === 0xdf && bytes[3] === 0xa3; return signed && await blobCrc32(blob) === asset.crc32; }
